import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Roboto_Flex } from "next/font/google";
import type { ReactNode } from "react";
import { GlobalLoader } from "@/components/GlobalLoader";
import { InitialLoader } from "@/components/InitialLoader";
import { LoadingProvider } from "@/providers/loading-context";
import "./globals.css";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-plus-jakarta-sans",
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

const robotoFlex = Roboto_Flex({
  subsets: ["latin"],
  variable: "--font-roboto-flex",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Rizki's Potofolio",
  description: "Generated by create next app",
  viewport: {
    width: "device-width",
    initialScale: 1,
    maximumScale: 5,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${plusJakartaSans.variable} ${robotoFlex.variable} font-sans antialiased`}
      >
        <LoadingProvider>
          <InitialLoader />
          <GlobalLoader />
          {children}
        </LoadingProvider>
      </body>
    </html>
  );
}
